//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.20 at 08:07:34 PM ICT 
//


package com.tinyolo.cxml.parsing.demo.jaxb.cxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dsX509IssuerName",
    "dsX509SerialNumber"
})
@XmlRootElement(name = "ds:X509IssuerSerial")
public class DsX509IssuerSerial {

    @XmlElement(name = "ds:X509IssuerName", required = true)
    protected String dsX509IssuerName;
    @XmlElement(name = "ds:X509SerialNumber", required = true)
    protected String dsX509SerialNumber;

    /**
     * Gets the value of the dsX509IssuerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsX509IssuerName() {
        return dsX509IssuerName;
    }

    /**
     * Sets the value of the dsX509IssuerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsX509IssuerName(String value) {
        this.dsX509IssuerName = value;
    }

    /**
     * Gets the value of the dsX509SerialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsX509SerialNumber() {
        return dsX509SerialNumber;
    }

    /**
     * Sets the value of the dsX509SerialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsX509SerialNumber(String value) {
        this.dsX509SerialNumber = value;
    }

}
