//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.20 at 08:07:34 PM ICT 
//


package com.tinyolo.cxml.parsing.demo.jaxb.cxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "qualityInspectionRequestHeader",
    "qualityInspectionRequestDetail"
})
@XmlRootElement(name = "QualityInspectionRequest")
public class QualityInspectionRequest {

    @XmlElement(name = "QualityInspectionRequestHeader", required = true)
    protected QualityInspectionRequestHeader qualityInspectionRequestHeader;
    @XmlElement(name = "QualityInspectionRequestDetail", required = true)
    protected QualityInspectionRequestDetail qualityInspectionRequestDetail;

    /**
     * Gets the value of the qualityInspectionRequestHeader property.
     * 
     * @return
     *     possible object is
     *     {@link QualityInspectionRequestHeader }
     *     
     */
    public QualityInspectionRequestHeader getQualityInspectionRequestHeader() {
        return qualityInspectionRequestHeader;
    }

    /**
     * Sets the value of the qualityInspectionRequestHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link QualityInspectionRequestHeader }
     *     
     */
    public void setQualityInspectionRequestHeader(QualityInspectionRequestHeader value) {
        this.qualityInspectionRequestHeader = value;
    }

    /**
     * Gets the value of the qualityInspectionRequestDetail property.
     * 
     * @return
     *     possible object is
     *     {@link QualityInspectionRequestDetail }
     *     
     */
    public QualityInspectionRequestDetail getQualityInspectionRequestDetail() {
        return qualityInspectionRequestDetail;
    }

    /**
     * Sets the value of the qualityInspectionRequestDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link QualityInspectionRequestDetail }
     *     
     */
    public void setQualityInspectionRequestDetail(QualityInspectionRequestDetail value) {
        this.qualityInspectionRequestDetail = value;
    }

}
