//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.20 at 08:08:13 PM ICT 
//


package com.tinyolo.cxml.parsing.demo.jaxb.fulfill;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "costTermValue",
    "scales"
})
@XmlRootElement(name = "ConditionType")
public class ConditionType {

    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlElement(name = "CostTermValue")
    protected CostTermValue costTermValue;
    @XmlElement(name = "Scales")
    protected Scales scales;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the costTermValue property.
     * 
     * @return
     *     possible object is
     *     {@link CostTermValue }
     *     
     */
    public CostTermValue getCostTermValue() {
        return costTermValue;
    }

    /**
     * Sets the value of the costTermValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link CostTermValue }
     *     
     */
    public void setCostTermValue(CostTermValue value) {
        this.costTermValue = value;
    }

    /**
     * Gets the value of the scales property.
     * 
     * @return
     *     possible object is
     *     {@link Scales }
     *     
     */
    public Scales getScales() {
        return scales;
    }

    /**
     * Sets the value of the scales property.
     * 
     * @param value
     *     allowed object is
     *     {@link Scales }
     *     
     */
    public void setScales(Scales value) {
        this.scales = value;
    }

}
