//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.20 at 08:08:13 PM ICT 
//


package com.tinyolo.cxml.parsing.demo.jaxb.fulfill;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "itemReference",
    "comments",
    "priority"
})
@XmlRootElement(name = "OrderStatusRequestItem")
public class OrderStatusRequestItem {

    @XmlAttribute(name = "rescheduleRequest")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String rescheduleRequest;
    @XmlAttribute(name = "rescheduleDate")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String rescheduleDate;
    @XmlElement(name = "ItemReference", required = true)
    protected ItemReference itemReference;
    @XmlElement(name = "Comments")
    protected Comments comments;
    @XmlElement(name = "Priority")
    protected Priority priority;

    /**
     * Gets the value of the rescheduleRequest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRescheduleRequest() {
        return rescheduleRequest;
    }

    /**
     * Sets the value of the rescheduleRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRescheduleRequest(String value) {
        this.rescheduleRequest = value;
    }

    /**
     * Gets the value of the rescheduleDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRescheduleDate() {
        return rescheduleDate;
    }

    /**
     * Sets the value of the rescheduleDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRescheduleDate(String value) {
        this.rescheduleDate = value;
    }

    /**
     * Gets the value of the itemReference property.
     * 
     * @return
     *     possible object is
     *     {@link ItemReference }
     *     
     */
    public ItemReference getItemReference() {
        return itemReference;
    }

    /**
     * Sets the value of the itemReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemReference }
     *     
     */
    public void setItemReference(ItemReference value) {
        this.itemReference = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link Comments }
     *     
     */
    public Comments getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Comments }
     *     
     */
    public void setComments(Comments value) {
        this.comments = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link Priority }
     *     
     */
    public Priority getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link Priority }
     *     
     */
    public void setPriority(Priority value) {
        this.priority = value;
    }

}
