//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.20 at 08:08:13 PM ICT 
//


package com.tinyolo.cxml.parsing.demo.jaxb.fulfill;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "productReplenishmentHeader",
    "productReplenishmentDetails",
    "extrinsic"
})
@XmlRootElement(name = "ProductReplenishmentMessage")
public class ProductReplenishmentMessage {

    @XmlElement(name = "ProductReplenishmentHeader", required = true)
    protected ProductReplenishmentHeader productReplenishmentHeader;
    @XmlElement(name = "ProductReplenishmentDetails", required = true)
    protected List<ProductReplenishmentDetails> productReplenishmentDetails;
    @XmlElement(name = "Extrinsic")
    protected List<Extrinsic> extrinsic;

    /**
     * Gets the value of the productReplenishmentHeader property.
     * 
     * @return
     *     possible object is
     *     {@link ProductReplenishmentHeader }
     *     
     */
    public ProductReplenishmentHeader getProductReplenishmentHeader() {
        return productReplenishmentHeader;
    }

    /**
     * Sets the value of the productReplenishmentHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductReplenishmentHeader }
     *     
     */
    public void setProductReplenishmentHeader(ProductReplenishmentHeader value) {
        this.productReplenishmentHeader = value;
    }

    /**
     * Gets the value of the productReplenishmentDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productReplenishmentDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductReplenishmentDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductReplenishmentDetails }
     * 
     * 
     */
    public List<ProductReplenishmentDetails> getProductReplenishmentDetails() {
        if (productReplenishmentDetails == null) {
            productReplenishmentDetails = new ArrayList<ProductReplenishmentDetails>();
        }
        return this.productReplenishmentDetails;
    }

    /**
     * Gets the value of the extrinsic property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extrinsic property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtrinsic().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extrinsic }
     * 
     * 
     */
    public List<Extrinsic> getExtrinsic() {
        if (extrinsic == null) {
            extrinsic = new ArrayList<Extrinsic>();
        }
        return this.extrinsic;
    }

}
