//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.20 at 08:08:13 PM ICT 
//


package com.tinyolo.cxml.parsing.demo.jaxb.fulfill;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "shipNoticeItemRetail"
})
@XmlRootElement(name = "ShipNoticeItemIndustry")
public class ShipNoticeItemIndustry {

    @XmlElement(name = "ShipNoticeItemRetail")
    protected ShipNoticeItemRetail shipNoticeItemRetail;

    /**
     * Gets the value of the shipNoticeItemRetail property.
     * 
     * @return
     *     possible object is
     *     {@link ShipNoticeItemRetail }
     *     
     */
    public ShipNoticeItemRetail getShipNoticeItemRetail() {
        return shipNoticeItemRetail;
    }

    /**
     * Sets the value of the shipNoticeItemRetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipNoticeItemRetail }
     *     
     */
    public void setShipNoticeItemRetail(ShipNoticeItemRetail value) {
        this.shipNoticeItemRetail = value;
    }

}
